### ISSUE TITLE
Asking for extra results

### ISSUE THREAD

**Issue by SonDaoDuy** [elijahcole/single-positive-multi-label#2]
Thank you for your great work!
I feel that the online training procedure is quite independent to the loss L_Epr. Have you tried to combine the online training procedure with other losses?
If it is convenient for you, can you provide some results on those combinations? 
And also I cannot find the supplementary file anywhere, can you release it?

**Comment by elijahcole** [comment]
Thanks for reading! 

You're right that the online label estimation framework could be combined with different losses, and I agree that it would be interesting to try some different approaches. Due to other commitments, I probably won't be able to do too many of those experiments myself in the near future. 

Regarding the supplementary material, I'm still finalizing a thing or two - sorry for the delay!

**Comment by coldmanck** [comment]
Hi @elijahcole how about the supplementary material? Thank you :-)
